"use client";

import { useState } from "react";
import { addProjectDomain, deleteProjectDomain, provisionProjectDomain, verifyProjectDomain, type ProjectDomain } from "@/lib/api";

export function DomainManager({ projectId, initialDomains, labels }: { projectId: string; initialDomains: ProjectDomain[]; labels: { title: string; add: string; auto: string; provisioned: string; verify: string; remove: string; verified: string; pending: string; placeholder: string; failed: string } }) {
  const [domains, setDomains] = useState(initialDomains);
  const [domain, setDomain] = useState("");
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  async function add() { setBusy(true); setMessage(""); try { const created = await addProjectDomain(projectId, domain); setDomains((items) => [{ ...created, verified_at: null }, ...items]); setDomain(""); setMessage(`TXT ${created.verification.name} = ${created.verification.value}`); } catch (error) { setMessage(error && typeof error === "object" && "error" in error ? String(error.error) : labels.failed); } finally { setBusy(false); } }
  async function autoConfigure() { setBusy(true); setMessage(""); try { const created = await provisionProjectDomain(projectId, domain); setDomains((items) => [{ ...created, verified_at: null }, ...items]); setDomain(""); setMessage(labels.provisioned); } catch (error) { setMessage(error && typeof error === "object" && "error" in error ? String(error.error) : labels.failed); } finally { setBusy(false); } }
  async function verify(id: string) { setBusy(true); try { await verifyProjectDomain(id); setDomains((items) => items.map((item) => item.id === id ? { ...item, verified_at: new Date().toISOString() } : item)); } catch (error) { setMessage(error && typeof error === "object" && "error" in error ? String(error.error) : labels.failed); } finally { setBusy(false); } }
  async function remove(id: string) { setBusy(true); try { await deleteProjectDomain(id); setDomains((items) => items.filter((item) => item.id !== id)); } finally { setBusy(false); } }
  return <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-sm font-semibold uppercase tracking-wide text-slate-500">{labels.title}</h2><div className="mt-3 flex flex-wrap gap-2"><input value={domain} onChange={(event) => setDomain(event.target.value)} placeholder={labels.placeholder} className="min-w-0 flex-1 rounded-lg border border-slate-300 px-3 py-2 text-sm" /><button type="button" disabled={busy || !domain.trim()} onClick={add} className="rounded-lg bg-brand-600 px-3 py-2 text-sm font-medium text-white disabled:opacity-50">{labels.add}</button><button type="button" disabled={busy || !domain.trim()} onClick={autoConfigure} className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-medium text-white disabled:opacity-50">{labels.auto}</button></div>{message && <p className="mt-2 break-all text-xs text-slate-500">{message}</p>}<div className="mt-4 space-y-2">{domains.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-slate-50 px-3 py-2 text-sm"><span>{item.domain} {item.verified_at ? <span className="text-green-700">{labels.verified}</span> : <span className="text-amber-700">{labels.pending}</span>}</span><span className="flex gap-3">{!item.verified_at && <button type="button" disabled={busy} onClick={() => verify(item.id)} className="text-brand-600">{labels.verify}</button>}<button type="button" disabled={busy} onClick={() => remove(item.id)} className="text-red-600">{labels.remove}</button></span></div>)}</div></section>;
}
